name = "pointing"
main = "js/_worker.js"
type = "javascript"
workers_dev = true
compatibility_date = "2024-03-20"

kv_namespaces = [
  { binding = "URLS", id = "c086767c204d4d7a8b5a549bc1c8e196" }
]

[[routes]]
pattern = "sorten.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "cyphers.game.naver.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "gamebulletin.nexon.game.naver.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "app-stg.gopay.co.id.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "www.langitmusik.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "Web.poe.garena.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "www.udemy.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "backdoor.farlight84miraclegames.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "Blog.x.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "partner.zoom.us.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "zoomgov.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "gomarketplacecontent-cf.zoom.us.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "investors.fb.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "bimbel.ruangguru.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.sea-sw.swiftserve.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "api.blibli.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "unnes.ac.id.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "fikom.esaunggul.ac.id.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "chat.sociomile.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "api.quipper.com.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "stripchat.page.sgdo7-one.k-chers.xyz"
custom_domain = true
[[routes]]
pattern = "ganecadigital.com.sgdo7-one.k-chers.xyz"
custom_domain = true
